name: My first Github Action
on: 
  # Rucne
  # workflow_dispatch:
 push:
jobs:
 Run-job:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Run assemble with Gradle Wrapper
      run: ./gradlew assemble
    
    - name: Run build with Gradle Wrapper
      run: ./gradlew clean build
      
    - name: Run javadoc with Gradle Wrapper
      run: ./gradlew javadoc 
         
