name: My first Github Action
on:
  # Rucne
  #workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  runs-on: ubuntu-latest
  steps:
    # Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}